services:
  airflow-webserver:
    image: apache/airflow:2.8.1
    container_name: airflow_webserver
    command: webserver
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./documents:/app/documents
      - /var/run/docker.sock:/var/run/docker.sock
      - ./airflow-data:/opt/airflow
      - ./.env:/opt/airflow/.env  # <-- ADD THIS LINE
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
    restart: always

  airflow-scheduler:
    image: apache/airflow:2.8.1
    container_name: airflow_scheduler
    command: scheduler
    volumes:
      - ./dags:/opt/airflow/dags
      - ./documents:/app/documents
      - /var/run/docker.sock:/var/run/docker.sock
      - ./airflow-data:/opt/airflow
      - ./.env:/opt/airflow/.env  # <-- AND ADD THIS LINE
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
    restart: always